# Generated by Django 5.1.2 on 2024-12-10 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcl', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiaclinica',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Historia Clínica', 'verbose_name_plural': 'Historias Clínicas'},
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='proximo_control',
        ),
        migrations.RemoveField(
            model_name='historiaclinica',
            name='tratamientos_aplicados',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='resultado_exitoso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='tratamiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='diagnostico',
            field=models.TextField(default='Sin diagnostico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'rol__nombre': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
