# Generated by Django 5.1.2 on 2024-12-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcl', '0002_alter_historiaclinica_options_and_more'),
        ('tratamientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='tratamiento',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='tratamientos',
            field=models.ManyToManyField(related_name='historias_clinicas', to='tratamientos.tratamiento'),
        ),
    ]
