# Generated by Django 5.1.2 on 2024-12-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcl', '0003_remove_historiaclinica_tratamiento_and_more'),
        ('tratamientos', '0002_remove_tratamiento_costo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='tratamientos',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='ttratamientos',
            field=models.ManyToManyField(blank=True, to='tratamientos.tratamiento'),
        ),
    ]
