# Generated by Django 5.1.2 on 2024-12-12 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcl', '0004_remove_historiaclinica_tratamientos_and_more'),
        ('tratamientos', '0003_remove_tratamiento_fecha_aplicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historiaclinica',
            name='ttratamientos',
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='fecha_aplicacion_tratamiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='tratamiento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tratamientos.tratamiento'),
        ),
    ]
