# Generated by Django 5.1.2 on 2024-12-12 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcl', '0005_remove_historiaclinica_ttratamientos_and_more'),
        ('tratamientos', '0003_remove_tratamiento_fecha_aplicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tratamientos.tratamiento'),
        ),
    ]
