# Generated by Django 5.1.2 on 2024-12-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_remove_paciente_tratamiento_alter_paciente_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='hcl',
            field=models.CharField(blank='True', max_length=10, unique=True),
        ),
    ]
