# Generated by Django 5.1.2 on 2025-07-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_alter_paciente_hcl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='hcl',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
