# Generated by Django 5.1.2 on 2024-12-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamiento',
            name='costo',
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='fecha_aplicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AplicacionTratamiento',
        ),
    ]
