# Generated by Django 5.1.2 on 2024-12-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0003_remove_tratamiento_fecha_aplicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
